# Generated by Django 5.2.1 on 2025-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دسته بندی')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='انتخاب url')),
            ],
        ),
    ]
