# Generated by Django 5.2.1 on 2025-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن تماس')),
                ('mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='تلفن همراه')),
                ('addres', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('about', models.CharField(blank=True, max_length=100, null=True, verbose_name='درباره ما')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
            ],
        ),
    ]
