# Generated by Django 5.2.1 on 2025-06-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='محصول ویژه'),
        ),
    ]
